### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by AstreaTSS** [AstreaTSS/PYTHIA#292]
This is an issue to track features I wish to add to PYTHIA, in *roughly* highest to lowest priority order. Please note that this isn't a strict list, and that I may be too busy to implement these at times.

- [x] Dice system based on UA
- [x] Rebrand current investigation system to "Truth Bullets system" to match with intended usage (ended up being "BDA investigation system")
  - [x] Rename `/investigate` to `/bda-investigate` and give adequate warning before doing so
- [x] Investigation/inventory system based on UA (Now called "Items system")
  - [x] Decide on proper name for system - the rebrand of the current system should help, but is that enough?
- [ ] Profile system based on Ultimate Assistant/UA
- [x] Gacha item rarities

**Comment by AstreaTSS** [comment]
Automatic announcements are tricker than they appear, and I may just continue to say "use some other bot like Carl that can do this" instead of trying to implement it myself. That being said, I haven't made a final decision about it yet.
